<?php

//常量
defined('CODE_NOT_ENGOUGH_PRODUCT') || define('CODE_NOT_ENGOUGH_PRODUCT', -4000);
defined('CODE_NOT_EXIST_CART') || define('CODE_NOT_EXIST_CART', -4004);
defined('CODE_ORDER_ERROR_FEE') || define('CODE_ORDER_ERROR_FEE', -5001);
defined('CODE_PRODUCT_EMPTY_ERROR') || define('CODE_PRODUCT_EMPTY_ERROR', -4002);
defined('CODE_PRODUCT_ERROR_FEE') || define('CODE_PRODUCT_ERROR_FEE', -4001);

//数组
if (!isset($GLOBALS['CODE_ADDR_GETLOCATION_ERROR'])) { $GLOBALS['CODE_ADDR_GETLOCATION_ERROR'] = []; }
$GLOBALS['CODE_ADDR_GETLOCATION_ERROR'] += array (
);
if (!isset($GLOBALS['CODE_ADDR_MATCH_ERROR'])) { $GLOBALS['CODE_ADDR_MATCH_ERROR'] = []; }
$GLOBALS['CODE_ADDR_MATCH_ERROR'] += array (
);
if (!isset($GLOBALS['CODE_ADDR_NUM_LIMIT'])) { $GLOBALS['CODE_ADDR_NUM_LIMIT'] = []; }
$GLOBALS['CODE_ADDR_NUM_LIMIT'] += array (
);
if (!isset($GLOBALS['CODE_CARD_ORDER_EMPTY_ERROR'])) { $GLOBALS['CODE_CARD_ORDER_EMPTY_ERROR'] = []; }
$GLOBALS['CODE_CARD_ORDER_EMPTY_ERROR'] += array (
);
if (!isset($GLOBALS['CODE_CART_MODIFIED_ERROR'])) { $GLOBALS['CODE_CART_MODIFIED_ERROR'] = []; }
$GLOBALS['CODE_CART_MODIFIED_ERROR'] += array (
);
if (!isset($GLOBALS['CODE_KUAIDI_ERROR'])) { $GLOBALS['CODE_KUAIDI_ERROR'] = []; }
$GLOBALS['CODE_KUAIDI_ERROR'] += array (
);
if (!isset($GLOBALS['CODE_MONEY_NO_ENOUGH'])) { $GLOBALS['CODE_MONEY_NO_ENOUGH'] = []; }
$GLOBALS['CODE_MONEY_NO_ENOUGH'] += array (
);
if (!isset($GLOBALS['CODE_MONEY_RECORD_ERROR'])) { $GLOBALS['CODE_MONEY_RECORD_ERROR'] = []; }
$GLOBALS['CODE_MONEY_RECORD_ERROR'] += array (
);
if (!isset($GLOBALS['CODE_NOT_ENABLED_SHOP'])) { $GLOBALS['CODE_NOT_ENABLED_SHOP'] = []; }
$GLOBALS['CODE_NOT_ENABLED_SHOP'] += array (
);
if (!isset($GLOBALS['CODE_NOT_EXIST_ADDRESS'])) { $GLOBALS['CODE_NOT_EXIST_ADDRESS'] = []; }
$GLOBALS['CODE_NOT_EXIST_ADDRESS'] += array (
);
if (!isset($GLOBALS['CODE_NOT_EXIST_BACK_ORDER'])) { $GLOBALS['CODE_NOT_EXIST_BACK_ORDER'] = []; }
$GLOBALS['CODE_NOT_EXIST_BACK_ORDER'] += array (
);
if (!isset($GLOBALS['CODE_NOT_EXIST_SHOP'])) { $GLOBALS['CODE_NOT_EXIST_SHOP'] = []; }
$GLOBALS['CODE_NOT_EXIST_SHOP'] += array (
);
if (!isset($GLOBALS['CODE_NOT_EXIST_USER'])) { $GLOBALS['CODE_NOT_EXIST_USER'] = []; }
$GLOBALS['CODE_NOT_EXIST_USER'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_CONTENT_LENGTH_ERROR'])) { $GLOBALS['CODE_ORDER_CONTENT_LENGTH_ERROR'] = []; }
$GLOBALS['CODE_ORDER_CONTENT_LENGTH_ERROR'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_ERROR_CALLBACK'])) { $GLOBALS['CODE_ORDER_ERROR_CALLBACK'] = []; }
$GLOBALS['CODE_ORDER_ERROR_CALLBACK'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_ERROR_OPERATION'])) { $GLOBALS['CODE_ORDER_ERROR_OPERATION'] = []; }
$GLOBALS['CODE_ORDER_ERROR_OPERATION'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_FEEDBACK_ALREADY'])) { $GLOBALS['CODE_ORDER_FEEDBACK_ALREADY'] = []; }
$GLOBALS['CODE_ORDER_FEEDBACK_ALREADY'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_NOT_ALLOW_FEEDBACK'])) { $GLOBALS['CODE_ORDER_NOT_ALLOW_FEEDBACK'] = []; }
$GLOBALS['CODE_ORDER_NOT_ALLOW_FEEDBACK'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_NOT_ALLOW_RETURN'])) { $GLOBALS['CODE_ORDER_NOT_ALLOW_RETURN'] = []; }
$GLOBALS['CODE_ORDER_NOT_ALLOW_RETURN'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_NOT_FEEDBACK'])) { $GLOBALS['CODE_ORDER_NOT_FEEDBACK'] = []; }
$GLOBALS['CODE_ORDER_NOT_FEEDBACK'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_RETURN_ALREADY'])) { $GLOBALS['CODE_ORDER_RETURN_ALREADY'] = []; }
$GLOBALS['CODE_ORDER_RETURN_ALREADY'] += array (
);
if (!isset($GLOBALS['CODE_ORDER_RETURN_ERROR'])) { $GLOBALS['CODE_ORDER_RETURN_ERROR'] = []; }
$GLOBALS['CODE_ORDER_RETURN_ERROR'] += array (
);
if (!isset($GLOBALS['CODE_PRODUCT_NOT_SALE_ERROR'])) { $GLOBALS['CODE_PRODUCT_NOT_SALE_ERROR'] = []; }
$GLOBALS['CODE_PRODUCT_NOT_SALE_ERROR'] += array (
);
if (!isset($GLOBALS['code_map'])) { $GLOBALS['code_map'] = []; }
$GLOBALS['code_map'] += array (
  -4000 => '商品库存不足',
  -4004 => '该商品已下架',
  -5001 => '总价不正确',
  -4002 => '商品为空',
  -4001 => '商品价格变动',
);
